[build]
  command = "git fetch --tags && export VITE_APP_VERSION=$(git describe --tags --long --abbrev=5 | sed 's/g//') && vite build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
